name: Gym Occupancy Logger

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  log-occupancy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run occupancy logger
        run: python logger/main.py

      - name: Commit CSVs every run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/${{ github.repository }}.git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add clubs_data/*.csv
          git commit -m "Update occupancy CSVs at $(date +'%Y-%m-%d %H:%M') [skip ci]"
          git push